/**
* @File Name : HAM_ConstantsUtil.cls
* @Description : This class is used to hold the hardcoded values used in the HAM Classes.
* @Author : Cube84 - Ashwin S
* @Last Modified By : Ashwin S
* @Last Modified On : Sep 03, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | Sep 03, 2025 |  Ashwin S | Initial Version - Done as part of Optimization
* 1.1 | Sep 30, 2025 |  Sachin | Added STUDENT - To implement logic to skip Residence Halls for 'Student' Primary Contact Type.
**/
public with sharing class HAM_ConstantsUtil {
    public static final String UNDERGRADUATE_DEGREE = 'Undergraduate_Degree';
    public static final String UNDERGRADUATE_MINOR = 'Undergraduate_Minor';
    public static final String POST_GRADUATE_DEGREE = 'Post_Graduate_Degree';
    public static final String UNDERGRADUATE_ATHLETICS = 'Undergraduate_Athletics';
    public static final String RESIDENCE_HALLS = 'Residence_Halls'; 
    public static final String STUDENT = 'Student';
    public static final String STUDENT_ORGANIZATIONS = 'Student_Organizations';
    public static final String SCHOOL_DEGREE_INFORMATION = 'School_Degree_Information';
    public static final String NON_SCHOOL_DEGREE_INFORMATION = 'Non_School_Degree_Information';
    public static final String STUDENT_NCAA_ATHLETICS = 'Student NCAA Athletics';
    public static final String STUDENT_HOUSING = 'Student Housing';
    public static final String STUDENT_CLUBS = 'Student Clubs';
    public static final String STUDENT_PRIVATE_SOCIETIES = 'Student Private Societies';
    public static final String PICKLIST = 'Picklist';
    public static final String CUSTOM = 'Custom';
    public static final String CURRENT = 'Current';
    public static final String CELL = 'Cell';
    public static final String PERSONAL = 'Personal'; 
    public static final String ALL_USERS = 'AllUsers'; 
    public static final String FOOTER = 'Footer'; 
    public static final String NAVBAR = 'NavBar'; 
    public static final String MY_AFFINITIES = 'My Affinities'; 
    public static final String LISTS = 'List'; 
    public static final String HARDCODED_STRING = 'Hardcoded String'; 
    public static final String MY_SERVICE = 'My Service'; 
    public static final String BIO_DATA = 'Bio Data'; 
    public static final String MY_CONNECT = 'My Connect'; 
    public static final String MY_PHILANTHROPY_HIGHLIGHT = 'My Philanthropy Highlight'; 
    public static final String MY_PHILANTHROPY_DETAIL = 'My Philanthropy Detail';

    public HAM_ConstantsUtil() {}
}